development:
  adapter: postgresql
  database: thestandardlibrarians_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: thestandardlibrarians_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: thestandardlibrarians_production
  pool: 5
  timeout: 5000
